name: SonarQube Code Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install SonarQube Scanner
        run: |
          npm install -g sonar-scanner

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=SimpleFastPyAPI \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://3.110.51.134:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
